apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: synapse
  name: synapse
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: synapse
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: synapse
    spec:
      containers:
      - image: docker-registry.default.svc:5000/pajak-riot/pajak-synapse
        name: synapse
        ports:
        - containerPort: 8448
        resources: {}
#        volumeMounts:
#        - mountPath: /media_store
#          name: synapse-data2
#        - mountPath: /uploads
#          name: synapse-data3
      restartPolicy: Always
      serviceAccountName: useroot
#      volumes:
#      - name: synapse-data2
#        persistentVolumeClaim:
#          claimName: claim-synapse2
#      - name: synapse-data3
#        persistentVolumeClaim:
#          claimName: claim-synapse3
