#!/bin/bash
DOCKER_REGISTRY=registry.private.i3dc.com:5000
PROJECT_NAME=pajak-riot
OCP_REGISTRY=docker-registry.default.svc:5000/$PROJECT_NAME

docker rmi ${1}
docker rmi $DOCKER_REGISTRY/${1}
docker rmi $OCP_REGISTRY/${2}
oc delete is ${2} 
