apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  capacity:
    storage: 5Gi 
  accessModes:
  - ReadWriteMany
  nfs: 
    path: /var/nfsshare/postgres
    server: 192.168.1.30
  persistentVolumeReclaimPolicy: Recycle 
