apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-riot
spec:
  capacity:
    storage: 5Gi 
  accessModes:
  - ReadWriteMany
  nfs: 
    path: /var/nfsshare/riot
    server: 192.168.1.30
  persistentVolumeReclaimPolicy: Recycle 
