apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-synapse-upload
spec:
  capacity:
    storage: 5Gi 
  accessModes:
  - ReadWriteMany
  nfs: 
    path: /var/nfsshare/synapse-upload
    server: 192.168.1.30
  persistentVolumeReclaimPolicy: Recycle 
